apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipe
  template:
    metadata:
      labels:
        app: pipe
    spec:
      containers:
      - name: pipe
        image: royjith/docker:version-1
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8501 
  selector:
    app: pipe
